version: '2'

services:

  discovery:
    image: "tenxtech/discovery"
    restart: "always"
    ports:
      - "8761:8761"

  mysql:
    image: "mysql:5.7"
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "vagrant"
      MYSQL_DATABASE: "vagrant"
      MYSQL_USER: "vagrant"
      MYSQL_PASSWORD: "vagrant"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
